### PR TITLE
Fix/4342 open and erase crash

### LINKED ISSUE #4342: The app crashes by tapping on 'Open and Erase' button when you are on Settings menu
## Steps to reproduce
1. Open Firefox Focus;
2. Load a webpage;
3. Enter on the Settings menu;
4. Press the home button;
5. Pull down the notification tray and tap on the 'Erase and Open' button;

### Expected behavior
The initial screen of Focus is displayed, with the previous webpage deleted;

### Actual behavior
The app crashes when you 'Erase and Open' from the Settings Menu;

### Device information
* Android device: Google Pixel (Android Q), Samsung Galaxy S8 (Android 9);
* Focus version: 8.0.16 GV 69.0
*  [pushlog](https://github.com/mozilla-mobile/focus-android/files/3533572/crash.focus.txt)

### PR DESCRIPTION
**Pull request by kkjasoncheung**
Closes [#4342](https://github.com/mozilla-mobile/focus-android/issues/4342)

Description:
Changes `launchMode` of `MainActivity` to `singleTask` and adds corresponding tests.

### CODE REVIEW

**Review by arvinth10 — APPROVED** [review]
LGTM

File: app/src/androidTest/java/org/mozilla/focus/activity/EraseAllUserDataTest.java [hunk 1]
```diff
@@ -137,7 +140,7 @@ public void systemBarTest() throws UiObjectNotFoundException {
     }
 
     @Test
-    public void systemBarHomeViewTest() throws UiObjectNotFoundException  {
+    public void systemBarHomeViewTest() throws UiObjectNotFoundException {
```
Comment (boiledbuns) [inline app/src/androidTest/java/org/mozilla/focus/activity/EraseAllUserDataTest.java]: nit: avoid making changes that don't affect pr

File: app/src/androidTest/java/org/mozilla/focus/activity/EraseAllUserDataTest.java [hunk 2]
```diff
@@ -159,12 +162,31 @@ public void systemBarHomeViewTest() throws UiObjectNotFoundException  {
         final String launcherPackage = TestHelper.mDevice.getLauncherPackageName();
         assertThat(launcherPackage, notNullValue());
         TestHelper.mDevice.wait(Until.hasObject(By.pkg(launcherPackage).depth(0)),
-                LAUNCH_TIMEOUT);
+            LAUNCH_TIMEOUT);
```
Comment (boiledbuns) [inline app/src/androidTest/java/org/mozilla/focus/activity/EraseAllUserDataTest.java]: nit: same as above

**Comment by boiledbuns** [comment]
LGTM, just a minor nit about modifying the spacing

**Review by poqwerty1998 — APPROVED** [review]

File: app/src/androidTest/java/org/mozilla/focus/activity/EraseAllUserDataTest.java (hunk 2 above)
Comment (kkjasoncheung) [reply app/src/androidTest/java/org/mozilla/focus/activity/EraseAllUserDataTest.java]: fixed
