### PR TITLE
Fix/4395 learn more back redirection

### LINKED ISSUE #4395: URL Autocomplete - The "back" action does not redirect the user correctly
## Steps to reproduce
1. Open Firefox Focus and navigate to "Settings"/"Search"/"URL Autocomplete".
2. Tap on the "Learn More" SUMO link.
3. Tap on the "Back" of the device.
### Expected behavior
The user is sent back to "URL Autocomplete" section.
### Actual behavior
The user is sent to the first page.
### Device information

* Android device: Google Pixel 2 (Android 9)
* Focus version: Focus / Klar - v8.0.22

Note:
It should be the same implementation as for "i" icon for "Add search engine" option.

### PR DESCRIPTION
**Pull request by arvinth10**
Closes [#4395](https://github.com/mozilla-mobile/focus-android/issues/4395)

Changes:
The Learn More button on any page now follows same behaviour as for "i" icon for "Add search engine" option. That is, it goes back to the previous activity instead of MainActivity. Corresponding tests are included as well.

### CODE REVIEW

File: app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java [hunk 1]
```diff
@@ -7,10 +7,12 @@
 
 import android.content.Context;
 import android.preference.PreferenceManager;
+
```
Comment (boiledbuns) [inline app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java]: nit: changed line

File: app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java [hunk 2]
```diff
@@ -86,4 +89,38 @@ public void AccessSettingsTest() {
         assertTrue(privacyHeading.exists());
         assertTrue(mozHeading.exists());
     }
+
+    @Test
+    public void BackRedirectionOnLearnMoreTest() {
+        UiObject searchHeading = TestHelper.mDevice.findObject(new UiSelector()
```
Comment (boiledbuns) [inline app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java:94]: I'm not super opposed to this way of testing the settings activity is visible when we press the back button, but this isn't ideal because it will be fragile wrt the settings activity (ie. it depends too much on the text in the activity). This might just be a case of YAGNI, but ideally all we should be checking is either:
a) a new session is not created when opening the "learn more" link
b) the InfoActitivy is created when opening the "learn more" link

File: app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java [hunk 3]
```diff
@@ -86,4 +89,38 @@ public void AccessSettingsTest() {
...
+
+        TestHelper.inlineAutocompleteEditText.waitForExists(waitingTime);
+        openSettings();
+
+        searchHeading.waitForExists(waitingTime);
+
+        try {
+            searchHeading.click();
+        } catch (UiObjectNotFoundException E) {
+            fail("Unable to find search heading on in settings menu");
```
Comment (kkjasoncheung) [inline app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java]: Is "on in settings menu" intended?

File: app/src/main/java/org/mozilla/focus/settings/LearnMoreSwitchPreference.kt [hunk 4]
```diff
@@ -36,15 +40,10 @@ abstract class LearnMoreSwitchPreference(context: Context?, attrs: AttributeSet?
...
-            if (context is ContextThemeWrapper) {
-                if ((context as ContextThemeWrapper).baseContext is Activity) {
-                    ((context as ContextThemeWrapper).baseContext as Activity).finish()
-                }
-            } else {
-                (context as? Activity)?.finish()
-            }
+            val url = getLearnMoreUrl()
+            val intent = InfoActivity.getIntentFor(context!!,
+                    url, context.getString(R.string.enable_search_suggestion_subtitle_learnmore))
```
Comment (boiledbuns) [inline app/src/main/java/org/mozilla/focus/settings/LearnMoreSwitchPreference.kt:45]: Curious, why do we use the `enable_search_suggestion_subtitle_learnmore` string?

**Review by boiledbuns — APPROVED** [review]
LTGM, just a few comments

File: app/src/main/java/org/mozilla/focus/settings/LearnMoreSwitchPreference.kt (hunk 4 above)
Comment (arvinth10) [reply app/src/main/java/org/mozilla/focus/settings/LearnMoreSwitchPreference.kt:45]: Thought 'Learn More' would be a suitable heading. Maybe there is a better option?

File: app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java (hunk 2 above)
Comment (mathu97) [reply app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java:94]: Not sure how to check what the current activity is in a UI test. There is a deprecated method ``TestHelper.mDevice.getCurrentActivityName()``,  but it seems to output a weird string for InfoActivity.

File: app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java (hunk 3 above)
Comment (mathu97) [reply app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java]: typo

File: app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java (hunk 2 above)
Comment (mathu97) [reply app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java:94]: but I agree, this test is pretty fragile

File: app/src/main/java/org/mozilla/focus/settings/LearnMoreSwitchPreference.kt (hunk 4 above)
Comment (boiledbuns) [reply app/src/main/java/org/mozilla/focus/settings/LearnMoreSwitchPreference.kt:45]: Nope, was just curious :)

**Review by kkjasoncheung — APPROVED** [review]
